/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Bitacora extends javax.swing.JFrame {

    public Bitacora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        audiProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movimiento = new javax.swing.JTextArea();
        audiFacturas = new javax.swing.JButton();
        audiventas = new javax.swing.JButton();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Volver.png"))); // NOI18N
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 640, 90, -1));

        audiProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Auditar Productos.png"))); // NOI18N
        audiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiProductosActionPerformed(evt);
            }
        });
        getContentPane().add(audiProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 60));

        movimiento.setColumns(20);
        movimiento.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        movimiento.setRows(5);
        jScrollPane1.setViewportView(movimiento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 920, 440));

        audiFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Auditar Facturas.png"))); // NOI18N
        audiFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiFacturasActionPerformed(evt);
            }
        });
        getContentPane().add(audiFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 190, 60));

        audiventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Auditar ventas.png"))); // NOI18N
        audiventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiventasActionPerformed(evt);
            }
        });
        getContentPane().add(audiventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 180, 60));

        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MovimientoProductos.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        PrincipalSistemas p = new PrincipalSistemas();
        p.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void audiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiProductosActionPerformed
        try {
            this.movimiento.setText(controlador.listarBitProductos().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Bitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_audiProductosActionPerformed

    private void audiFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiFacturasActionPerformed
        try {
            this.movimiento.setText(controlador.listarFacturas().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Bitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_audiFacturasActionPerformed

    private void audiventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiventasActionPerformed
        try {
            this.movimiento.setText(controlador.listarDetalles().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Bitacora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_audiventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bitacora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bitacora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bitacora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bitacora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bitacora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Volver;
    private javax.swing.JButton audiFacturas;
    private javax.swing.JButton audiProductos;
    private javax.swing.JButton audiventas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea movimiento;
    // End of variables declaration//GEN-END:variables
    Controlador controlador = new Controlador();
}
