/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ConsultarProducto extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarProducto
     */
    public ConsultarProducto(int numero) {
        this.numero = numero;
        this.controlador = new Controlador();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTextArea();
        Abarrotes = new javax.swing.JButton();
        Mercancia = new javax.swing.JButton();
        Personal = new javax.swing.JButton();
        Fresco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, 90, -1));

        productos.setColumns(20);
        productos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        productos.setRows(5);
        jScrollPane1.setViewportView(productos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 920, 410));

        Abarrotes.setText("Abarrotes");
        Abarrotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbarrotesActionPerformed(evt);
            }
        });
        getContentPane().add(Abarrotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 40));

        Mercancia.setText("Mercancia");
        Mercancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercanciaActionPerformed(evt);
            }
        });
        getContentPane().add(Mercancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 110, 40));

        Personal.setText("Personal");
        Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalActionPerformed(evt);
            }
        });
        getContentPane().add(Personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 110, 40));

        Fresco.setText("Fresco");
        Fresco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrescoActionPerformed(evt);
            }
        });
        getContentPane().add(Fresco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 110, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Lista de productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Buscar por código o descripción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        getContentPane().add(campoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 180, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 80, -1));

        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen_1.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 940, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        switch (numero) {
            case 1:
                GerenteAbarrote ga = new GerenteAbarrote();
                ga.setVisible(true);
                this.setVisible(false);
                break;
            case 4:
                GerenteFresco gf = new GerenteFresco();
                gf.setVisible(true);
                this.setVisible(false);
                break;
            case 5:
                GerenteGeneral gg = new GerenteGeneral();
                gg.setVisible(true);
                this.setVisible(false);
                break;
            case 2:
                GerenteMercancia gm = new GerenteMercancia();
                gm.setVisible(true);
                this.setVisible(false);
                break;
            case 3:
                GerentePersonal gp = new GerentePersonal();
                gp.setVisible(true);
                this.setVisible(false);
                break;
            case 6:
                PrincipalCajero p = new PrincipalCajero();
                p.setVisible(true);
                this.setVisible(false);
                break;
            case 7:
                PrincipalSistemas s = new PrincipalSistemas();
                s.setVisible(true);
                this.setVisible(false);
                break;
            default:
                Login vista = new Login();
                vista.setVisible(true);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_VolverActionPerformed

    private void AbarrotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbarrotesActionPerformed
        try {
            productos.setText(this.controlador.listaAbarrotes().toString());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AbarrotesActionPerformed

    private void MercanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercanciaActionPerformed
        try {
            productos.setText(this.controlador.listaMercancia().toString());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MercanciaActionPerformed

    private void PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalActionPerformed
        try {
            productos.setText(this.controlador.listaPersonal().toString());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PersonalActionPerformed

    private void FrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrescoActionPerformed
        try {
            productos.setText(this.controlador.listaFresco().toString());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FrescoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            if (controlador.verificarCodigo(this.campoBuscar.getText())) {
                this.productos.setText(controlador.recuperarProductoPorCod(this.campoBuscar.getText()));
            } else {
                if (controlador.verificarDescripcion(this.campoBuscar.getText())) {
                    this.productos.setText(controlador.recuperarProductoPorDescrip(this.campoBuscar.getText()));
                } else {
                    Object[] message = {"Codigo o descripcion no valido"};
                    JOptionPane.showMessageDialog(ConsultarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int numero = 0;
                new ConsultarProducto(numero).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abarrotes;
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Fresco;
    private javax.swing.JButton Mercancia;
    private javax.swing.JButton Personal;
    private javax.swing.JButton Volver;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea productos;
    // End of variables declaration//GEN-END:variables
    int numero;
    Controlador controlador;
}
