/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Facturar extends javax.swing.JFrame {


     public Facturar(int numero) {
        this.numero = numero;
        this.controlador = new Controlador();
        initComponents();
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        codigoprod = new javax.swing.JTextField();
        cantProd = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTextArea();
        deleteP = new javax.swing.JButton();
        genFact = new javax.swing.JButton();
        Volver1 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        totalText = new javax.swing.JLabel();
        FondoCliente = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinner1.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 82, 31));

        codigoprod.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        codigoprod.setForeground(new java.awt.Color(0, 0, 0));
        codigoprod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(codigoprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 141, 32));

        cantProd.setFont(new java.awt.Font("Haettenschweiler", 0, 24)); // NOI18N
        cantProd.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        getContentPane().add(cantProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 106, 35));

        productos.setEditable(false);
        productos.setColumns(20);
        productos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        productos.setRows(5);
        jScrollPane1.setViewportView(productos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 950, 390));

        deleteP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Eliminar.png"))); // NOI18N
        deleteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePActionPerformed(evt);
            }
        });
        getContentPane().add(deleteP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 110, 40));

        genFact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Factura.png"))); // NOI18N
        genFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFactActionPerformed(evt);
            }
        });
        getContentPane().add(genFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 662, 110, 50));

        Volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Volver.png"))); // NOI18N
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });
        getContentPane().add(Volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 90, 40));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Agregar.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 140, 40));

        totalText.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        totalText.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(totalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 156, 40));

        FondoCliente.setForeground(new java.awt.Color(153, 255, 153));
        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Facturar.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        controlador.vaciarCarro();
        this.setVisible(false);
        switch (numero) {
            case 1:
            GerenteAbarrote ga = new GerenteAbarrote();
            ga.setVisible(true);
            this.setVisible(false);
            break;
            case 4:
            GerenteFresco gf = new GerenteFresco();
            gf.setVisible(true);
            this.setVisible(false);
            break;
            case 5:
            GerenteGeneral gg = new GerenteGeneral();
            gg.setVisible(true);
            this.setVisible(false);
            break;
            case 2:
            GerenteMercancia gm = new GerenteMercancia();
            gm.setVisible(true);
            this.setVisible(false);
            break;
            case 3:
            GerentePersonal gp = new GerentePersonal();
            gp.setVisible(true);
            this.setVisible(false);
            break;
            case 6:
            PrincipalCajero p = new PrincipalCajero();
            p.setVisible(true);
            this.setVisible(false);
            break;
            case 7:
            PrincipalSistemas s = new PrincipalSistemas();
            s.setVisible(true);
            this.setVisible(false);
            break;
            default:
            Login vista = new Login();
            vista.setVisible(true);
            this.setVisible(false);
            break;
        }
    }//GEN-LAST:event_Volver1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
         try {
             
             // TODO add your handling code here:
             controlador.meterAlCarro(this.codigoprod.getText(),(Float)this.cantProd.getValue());
             
             this.productos.setText(controlador.parseaLista(controlador.todoCarrito()));
             this.codigoprod.setText("");
             this.cantProd.setValue(0f);
             this.totalText.setText(String.valueOf(controlador.suma()));
         } catch (SQLException ex) {
             //Logger.getLogger(Facturar.class.getName()).log(Level.SEVERE, null, ex);
             Object[] mensaje = {"Producto no encontrado o supera cantidad"};
             JOptionPane.showMessageDialog(Facturar.this, mensaje, "Error", JOptionPane.OK_OPTION);
         }
    }//GEN-LAST:event_addActionPerformed

    private void deletePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePActionPerformed
         try {
             // TODO add your handling code here:
             controlador.sacarDelCarro(this.codigoprod.getText());
             this.productos.setText(controlador.parseaLista(controlador.todoCarrito()));
             this.totalText.setText(String.valueOf(controlador.suma()));
         } catch (Exception ex) {
             Object[] mensaje = {"Producto no encontrado en factura"};
             JOptionPane.showMessageDialog(Facturar.this, mensaje, "Error", JOptionPane.OK_OPTION);
         }
        this.codigoprod.setText("");
        this.cantProd.setValue(0f);
        
    }//GEN-LAST:event_deletePActionPerformed

    private void genFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFactActionPerformed
         try {
             // TODO add your handling code here:
             controlador.enviar((Integer)this.jSpinner1.getValue());
             controlador.vaciarCarro();
             this.productos.setText("");
             Object[] mensaje = {"Factura ingresada con exito"};
             JOptionPane.showMessageDialog(Facturar.this, mensaje, "Hecho!", JOptionPane.OK_OPTION);
         } catch (SQLException ex) {
              Object[] mensaje = {"Factura no se pudo ingresar"};
             JOptionPane.showMessageDialog(Facturar.this, mensaje, "Error", JOptionPane.OK_OPTION);
         }
    }//GEN-LAST:event_genFactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int numero = 0;
                new Facturar(numero).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Volver1;
    private javax.swing.JButton add;
    private javax.swing.JSpinner cantProd;
    private javax.swing.JTextField codigoprod;
    private javax.swing.JButton deleteP;
    private javax.swing.JButton genFact;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea productos;
    private javax.swing.JLabel totalText;
    // End of variables declaration//GEN-END:variables

    int numero;
    Controlador controlador;
}
