/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import logic.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class InsertarProducto extends javax.swing.JFrame {

    /**
     * Creates new form InsertarEAN
     */
    public InsertarProducto(int pagina) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pagina = pagina;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoArea = new javax.swing.JTextField();
        CampoPrecio = new javax.swing.JTextField();
        CampoCantidad = new javax.swing.JTextField();
        CampoCodigo = new javax.swing.JTextField();
        CampoPeso = new javax.swing.JTextField();
        CampoDescripcion = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoArea.setBackground(new java.awt.Color(51, 51, 51));
        CampoArea.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoArea.setForeground(new java.awt.Color(255, 255, 255));
        CampoArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoArea.setPreferredSize(new java.awt.Dimension(35, 45));
        CampoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAreaActionPerformed(evt);
            }
        });
        getContentPane().add(CampoArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 310, -1));

        CampoPrecio.setBackground(new java.awt.Color(51, 51, 51));
        CampoPrecio.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        CampoPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoPrecio.setPreferredSize(new java.awt.Dimension(35, 45));
        CampoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 310, -1));

        CampoCantidad.setBackground(new java.awt.Color(51, 51, 51));
        CampoCantidad.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoCantidad.setForeground(new java.awt.Color(255, 255, 255));
        CampoCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoCantidad.setPreferredSize(new java.awt.Dimension(35, 45));
        CampoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 310, -1));

        CampoCodigo.setBackground(new java.awt.Color(51, 51, 51));
        CampoCodigo.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoCodigo.setForeground(new java.awt.Color(255, 255, 255));
        CampoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoCodigo.setPreferredSize(new java.awt.Dimension(35, 45));
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 310, -1));

        CampoPeso.setBackground(new java.awt.Color(51, 51, 51));
        CampoPeso.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoPeso.setForeground(new java.awt.Color(255, 255, 255));
        CampoPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoPeso.setPreferredSize(new java.awt.Dimension(35, 45));
        CampoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 310, -1));

        CampoDescripcion.setBackground(new java.awt.Color(51, 51, 51));
        CampoDescripcion.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        CampoDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoDescripcion.setPreferredSize(new java.awt.Dimension(35, 45));
        getContentPane().add(CampoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 310, -1));

        Modificar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Insertar.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, -1, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Salir.png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 100, -1));

        FondoCliente.setForeground(new java.awt.Color(153, 255, 153));
        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/InsertarProducto.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoAreaActionPerformed

    private void CampoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecioActionPerformed

    private void CampoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCantidadActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed

    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        try {
            if (this.camposLlenos()) {

                //     public Producto(String codigo, String descripcion, int cantidad, float precio, float peso, String area ,int plu ,float ean ) {
                Producto nuevo_producto = new Producto(
                        this.CampoCodigo.getText(),
                        this.CampoDescripcion.getText(),
                        Integer.parseInt(this.CampoCantidad.getText()),
                        Float.parseFloat(this.CampoPrecio.getText()),
                        Float.parseFloat(this.CampoPeso.getText()),
                        this.CampoArea.getText()
                );


                controlador.insertarProducto(nuevo_producto);
                Object[] message = {"Accion Realizada Correctamente"};
                JOptionPane.showMessageDialog(null, "Accion realizada Correctamente!");

                limpiarCampos();
            } else {
                Object[] message = {"Hay campos vacios"};
                JOptionPane.showMessageDialog(InsertarProducto.this, message, "Error", JOptionPane.OK_OPTION);
            }
        } catch (SQLException | NumberFormatException ex) {
            Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
            JOptionPane.showMessageDialog(InsertarProducto.this, message, "Error", JOptionPane.OK_OPTION);
            limpiarCampos();
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private boolean camposLlenos() {

        return (!this.CampoCodigo.getText().isEmpty()
                && !this.CampoCantidad.getText().isEmpty()
                && !this.CampoDescripcion.getText().isEmpty()
                && !this.CampoPrecio.getText().isEmpty()
                && !this.CampoArea.getText().isEmpty());
    }

    private void limpiarCampos() {
        this.CampoCodigo.setText(null);
        this.CampoDescripcion.setText(null);
        this.CampoCantidad.setText(null);
        this.CampoPrecio.setText(null);
        this.CampoArea.setText(null);
        this.CampoPeso.setText(null);
    }

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        switch (pagina) {
            case 5:
                this.setVisible(false);
                GerenteGeneral gg = new GerenteGeneral();
                gg.setVisible(true);
                break;
            case 7:
                this.setVisible(false);
                PrincipalSistemas ps = new PrincipalSistemas();
                ps.setVisible(true);
                break;
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void CampoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int n = 0;
                new InsertarProducto(n).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoArea;
    private javax.swing.JTextField CampoCantidad;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoDescripcion;
    private javax.swing.JTextField CampoPeso;
    private javax.swing.JTextField CampoPrecio;
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables
    int pagina;
    Controlador controlador = new Controlador();
}
