/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import entidades.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class InsertarPLU extends javax.swing.JFrame {

    /**
     * Creates new form InsertarPLU
     */
    public InsertarPLU(int numero) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.numero = numero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoPeso = new javax.swing.JTextField();
        CampoPrecio = new javax.swing.JTextField();
        CampoDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        Insertar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoPeso.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 310, -1));

        CampoPrecio.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 310, -1));

        CampoDescripcion.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        getContentPane().add(CampoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 310, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Peso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Ingresar datos del producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        CampoCodigo.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        getContentPane().add(CampoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 310, -1));

        Insertar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        getContentPane().add(Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 100, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Código");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 90, -1));

        FondoCliente.setForeground(new java.awt.Color(153, 255, 153));
        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen_1.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 900, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesoActionPerformed

    private void CampoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecioActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        if (!this.CampoCodigo.getText().isEmpty() && !this.CampoDescripcion.getText().isEmpty()
                && !this.CampoPrecio.getText().isEmpty() && !this.CampoPeso.getText().isEmpty()) {
            try {
                controlador.insertarProducto(new Producto(this.CampoCodigo.getText(), this.CampoDescripcion.getText(),
                        0, Float.parseFloat(this.CampoPrecio.getText()), "-", Float.parseFloat(this.CampoPeso.getText()), "Fresco"));
            } catch (SQLException | NumberFormatException ex) {
                Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
                JOptionPane.showMessageDialog(InsertarPLU.this, message, "Error", JOptionPane.OK_OPTION);
            }
            limpiarCampos();
        } else {
            Object[] message = {"Hay campos vacios"};
            JOptionPane.showMessageDialog(InsertarPLU.this, message, "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_InsertarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        switch (numero) {
            case 5:
                this.setVisible(false);
                GerenteGeneral gg = new GerenteGeneral();
                gg.setVisible(true);
                break;
            case 7:
                this.setVisible(false);
                PrincipalSistemas ps = new PrincipalSistemas();
                ps.setVisible(true);
                break;
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void limpiarCampos() {
        this.CampoCodigo.setText(null);
        this.CampoDescripcion.setText(null);
        this.CampoPrecio.setText(null);
        this.CampoPeso.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarPLU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarPLU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarPLU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarPLU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int numero = 0;
                new InsertarPLU(numero).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoDescripcion;
    private javax.swing.JTextField CampoPeso;
    private javax.swing.JTextField CampoPrecio;
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Insertar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    int numero;
    Controlador controlador = new Controlador();
}
