/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import entidades.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ModificarEAN extends javax.swing.JFrame {

    /**
     * Creates new form ModificarEAN
     */
    public ModificarEAN(int numero, int numero2) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.numero = numero;
        this.numero2 = numero2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        CampoTipo = new javax.swing.JTextField();
        CampoPrecio = new javax.swing.JTextField();
        CampoCantidad = new javax.swing.JTextField();
        CampoDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 90, -1));

        CampoTipo.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTipoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 310, -1));

        CampoPrecio.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 310, -1));

        CampoCantidad.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 310, -1));

        CampoDescripcion.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        getContentPane().add(CampoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 310, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Tipo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Datos a modificar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        CampoCodigo.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 310, -1));

        Modificar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Ingrese el código del producto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        FondoCliente.setForeground(new java.awt.Color(153, 255, 153));
        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen_1.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -40, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        switch (numero) {
            case 5:
                GerenteGeneral gg = new GerenteGeneral();
                gg.setVisible(true);
                break;
            case 7:
                PrincipalSistemas s = new PrincipalSistemas();
                s.setVisible(true);
                break;
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void CampoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTipoActionPerformed

    private void CampoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecioActionPerformed

    private void CampoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCantidadActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        switch (numero2) {
            case 1: {
                try {
                    if (controlador.verificarCodigo(this.CampoCodigo.getText())) {
//                        controlador.modificarProducto(new Producto(this.CampoCodigo.getText(), this.CampoDescripcion.getText(),
//                                Integer.parseInt(this.CampoCantidad.getText()), Float.parseFloat(this.CampoPrecio.getText()),
//                                this.CampoTipo.getText(), 0, "Abarrote"));
                        limpiarCampos();
                    } else {
                        Object[] message = {"Codigo no valido para actualizar"};
                        JOptionPane.showMessageDialog(ModificarEAN.this, message, "Error", JOptionPane.OK_OPTION);
                        limpiarCampos();
                    }
                    break;
                } catch (SQLException | NumberFormatException ex) {
                    Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
                    JOptionPane.showMessageDialog(ModificarEAN.this, message, "Error", JOptionPane.OK_OPTION);
                    limpiarCampos();
                    break;
                }
            }
            case 2: {
                try {
                    if (controlador.verificarCodigo(this.CampoCodigo.getText())) {
//                        controlador.modificarProducto(new Producto(this.CampoCodigo.getText(), this.CampoDescripcion.getText(),
//                                Integer.parseInt(this.CampoCantidad.getText()), Float.parseFloat(this.CampoPrecio.getText()),
//                                this.CampoTipo.getText(), 0, "Mercancia"));
                        limpiarCampos();
                    } else {
                        Object[] message = {"Codigo no valido para actualizar"};
                        JOptionPane.showMessageDialog(ModificarEAN.this, message, "Error", JOptionPane.OK_OPTION);
                        limpiarCampos();
                    }
                } catch (SQLException | NumberFormatException ex) {
                    Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
                    JOptionPane.showMessageDialog(ModificarEAN.this, message, "Error", JOptionPane.OK_OPTION);
                    limpiarCampos();
                    break;
                }
            }
            break;

            case 3: {
                try {
                    if (controlador.verificarCodigo(this.CampoCodigo.getText())) {
//                        controlador.modificarProducto(new Producto(this.CampoCodigo.getText(), this.CampoDescripcion.getText(),
//                                Integer.parseInt(this.CampoCantidad.getText()), Float.parseFloat(this.CampoPrecio.getText()),
//                                this.CampoTipo.getText(), 0, "Personal"));
                        limpiarCampos();
                    } else {
                        Object[] message = {"Codigo no valido para actualizar"};
                        JOptionPane.showMessageDialog(ModificarEAN.this, message, "Error", JOptionPane.OK_OPTION);
                        limpiarCampos();
                    }
                    break;
                } catch (SQLException | NumberFormatException ex) {
                    Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
                    JOptionPane.showMessageDialog(ModificarEAN.this, message, "Error", JOptionPane.OK_OPTION);
                    limpiarCampos();
                    break;
                }
            }
            default:
                Object[] message = {"Codigo no valido para actualizar"};
                JOptionPane.showMessageDialog(ModificarEAN.this, message, "Error", JOptionPane.OK_OPTION);
                break;
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed

    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void limpiarCampos() {
        this.CampoCodigo.setText(null);
        this.CampoDescripcion.setText(null);
        this.CampoCantidad.setText(null);
        this.CampoPrecio.setText(null);
        this.CampoTipo.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int i = 0;
                int j = 0;
                new ModificarEAN(i, j).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCantidad;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoDescripcion;
    private javax.swing.JTextField CampoPrecio;
    private javax.swing.JTextField CampoTipo;
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    Controlador controlador = new Controlador();
    int numero;
    int numero2;
}
