
package vista;

import controlador.Controlador;
import logic.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ModificarGerentes extends javax.swing.JFrame {

    /**
     * Creates new form ModificarEAN
     */
    public ModificarGerentes(int numero) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.numero = numero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        CampoPeso = new javax.swing.JTextField();
        CampoPrecio = new javax.swing.JTextField();
        CampoCantidad = new javax.swing.JTextField();
        CampoDescripcion = new javax.swing.JTextField();
        CampoCodigo = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        CampoArea = new javax.swing.JTextField();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Salir.png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, 110, -1));

        CampoPeso.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoPeso.setForeground(new java.awt.Color(0, 0, 0));
        CampoPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoPeso.setPreferredSize(new java.awt.Dimension(40, 55));
        CampoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 310, -1));

        CampoPrecio.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoPrecio.setForeground(new java.awt.Color(0, 0, 0));
        CampoPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoPrecio.setPreferredSize(new java.awt.Dimension(40, 55));
        CampoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(CampoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 310, -1));

        CampoCantidad.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoCantidad.setForeground(new java.awt.Color(0, 0, 0));
        CampoCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoCantidad.setPreferredSize(new java.awt.Dimension(40, 55));
        CampoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 310, -1));

        CampoDescripcion.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        CampoDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoDescripcion.setPreferredSize(new java.awt.Dimension(40, 55));
        getContentPane().add(CampoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 310, -1));

        CampoCodigo.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoCodigo.setForeground(new java.awt.Color(0, 0, 0));
        CampoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoCodigo.setPreferredSize(new java.awt.Dimension(40, 55));
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 310, -1));

        Modificar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/modificar.png"))); // NOI18N
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        CampoArea.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        CampoArea.setForeground(new java.awt.Color(0, 0, 0));
        CampoArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoArea.setPreferredSize(new java.awt.Dimension(40, 55));
        CampoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAreaActionPerformed(evt);
            }
        });
        getContentPane().add(CampoArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 310, -1));

        FondoCliente.setForeground(new java.awt.Color(153, 255, 153));
        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ModificarEAN.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        switch (numero) {
            case 5:
                GerenteGeneral gg = new GerenteGeneral();
                gg.setVisible(true);
                break;
            case 7:
                PrincipalSistemas s = new PrincipalSistemas();
                s.setVisible(true);
                break;
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void CampoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesoActionPerformed

    private void CampoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecioActionPerformed

    private void CampoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCantidadActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        try {
            if (controlador.verificarCodigo(this.CampoCodigo.getText())) {
                Producto prod = controlador.recuperarProductoPorCodOb(this.CampoCodigo.getText());
                prod.setDescripcion(this.CampoDescripcion.getText());
                prod.setCantidad(Integer.parseInt(this.CampoCantidad.getText()));
                prod.setPrecio(Float.parseFloat(this.CampoPrecio.getText()));
                prod.setArea(this.CampoArea.getText());
                prod.setPeso(Float.parseFloat(this.CampoPeso.getText()));
                controlador.modificarProducto(prod);
                JOptionPane.showMessageDialog(null, "Accion realizada Correctamente!");
                limpiarCampos();
            } else {
                Object[] message = {"Codigo no valido para actualizar"};
                JOptionPane.showMessageDialog(ModificarGerentes.this, message, "Error", JOptionPane.OK_OPTION);
                limpiarCampos();
            }

        } catch (SQLException | NumberFormatException ex) {
            Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
            JOptionPane.showMessageDialog(ModificarGerentes.this, message, "Error", JOptionPane.OK_OPTION);
            limpiarCampos();

        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed

    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void CampoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoAreaActionPerformed

    private void limpiarCampos() {
        this.CampoCodigo.setText(null);
        this.CampoDescripcion.setText(null);
        this.CampoCantidad.setText(null);
        this.CampoPrecio.setText(null);
        this.CampoPeso.setText(null);
        this.CampoArea.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarGerentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int i = 0;
                new ModificarGerentes(i).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoArea;
    private javax.swing.JTextField CampoCantidad;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoDescripcion;
    private javax.swing.JTextField CampoPeso;
    private javax.swing.JTextField CampoPrecio;
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables
    Controlador controlador = new Controlador();
    int numero;

}
