/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import entidades.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProducto
     */
    public ModificarProducto(int numero, int numero2) {
        initComponents();
        this.numero = numero;
        this.numero2 = numero2;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CampoCantidad = new javax.swing.JTextField();
        CampoDescripcion = new javax.swing.JTextField();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 90, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Datos a modificar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        CampoCodigo.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 310, -1));

        btnModificar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Ingrese el código del producto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        CampoCantidad.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CampoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 310, -1));

        CampoDescripcion.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        getContentPane().add(CampoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 310, -1));

        FondoCliente.setForeground(new java.awt.Color(153, 255, 153));
        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen_1.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -40, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        switch (numero) {
            case 1:
                GerenteAbarrote gg = new GerenteAbarrote();
                gg.setVisible(true);
                break;
            case 2:
                GerenteMercancia s = new GerenteMercancia();
                s.setVisible(true);
                break;
            case 3:
                GerentePersonal ss = new GerentePersonal();
                ss.setVisible(true);
                break;
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed

    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        switch (numero2) {
            case 1: {
                try {
                    if (controlador.verificarCodigo(this.CampoCodigo.getText())) {
                        controlador.modificarProducto(new Producto(this.CampoCodigo.getText(), this.CampoDescripcion.getText(),
                                Integer.parseInt(this.CampoCantidad.getText()), controlador.recuperarProducto(this.CampoCodigo.getText()).getPrecio(),
                                controlador.recuperarProducto(this.CampoCodigo.getText()).getTipo(), 0, "Abarrote"));
                        limpiarCampos();
                    } else {
                        Object[] message = {"Codigo no valido para actualizar"};
                        JOptionPane.showMessageDialog(ModificarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                        limpiarCampos();
                    }
                    break;
                } catch (SQLException | NumberFormatException ex) {
                    Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
                    JOptionPane.showMessageDialog(ModificarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                    limpiarCampos();
                    break;
                }
            }
            case 2: {
                try {
                    if (controlador.verificarCodigo(this.CampoCodigo.getText())) {
                        controlador.modificarProducto(new Producto(this.CampoCodigo.getText(), this.CampoDescripcion.getText(),
                                Integer.parseInt(this.CampoCantidad.getText()), controlador.recuperarProducto(this.CampoCodigo.getText()).getPrecio(),
                                controlador.recuperarProducto(this.CampoCodigo.getText()).getTipo(), 0, "Mercancia"));
                        limpiarCampos();
                    } else {
                        Object[] message = {"Codigo no valido para actualizar"};
                        JOptionPane.showMessageDialog(ModificarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                        limpiarCampos();
                    }
                } catch (SQLException | NumberFormatException ex) {
                    Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
                    JOptionPane.showMessageDialog(ModificarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                    limpiarCampos();
                    break;
                }
            }
            break;

            case 3: {
                try {
                    if (controlador.verificarCodigo(this.CampoCodigo.getText())) {
                        controlador.modificarProducto(new Producto(this.CampoCodigo.getText(), this.CampoDescripcion.getText(),
                                Integer.parseInt(this.CampoCantidad.getText()), controlador.recuperarProducto(this.CampoCodigo.getText()).getPrecio(),
                                controlador.recuperarProducto(this.CampoCodigo.getText()).getTipo(), 0, "Personal"));
                        limpiarCampos();
                    } else {
                        Object[] message = {"Codigo no valido para actualizar"};
                        JOptionPane.showMessageDialog(ModificarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                        limpiarCampos();
                    }
                    break;
                } catch (SQLException | NumberFormatException ex) {
                    Object[] message = {"Código ya existe u ocurrió error al ingresar un dato"};
                    JOptionPane.showMessageDialog(ModificarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                    limpiarCampos();
                    break;
                }
            }
            default:
                Object[] message = {"Codigo no valido para actualizar"};
                JOptionPane.showMessageDialog(ModificarProducto.this, message, "Error", JOptionPane.OK_OPTION);
                break;
        }
    }

    private void limpiarCampos() {
        this.CampoCodigo.setText(null);
        this.CampoDescripcion.setText(null);
        this.CampoCantidad.setText(null);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void CampoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int numero3 = 0;
                new ModificarProducto(numero3, numero3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCantidad;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoDescripcion;
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Salir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    Controlador controlador = new Controlador();
    int numero;
    int numero2;
}
