/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

public class PrincipalSistemas extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalSistemas
     */
    public PrincipalSistemas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bitacora = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        FondoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Consultar producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Consultar bitácora");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 90, -1));

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 90, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Borrar producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Insertar producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Que desea realizar Ingeniero(a):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 460, 40));

        bitacora.setText("Consultar");
        bitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitacoraActionPerformed(evt);
            }
        });
        getContentPane().add(bitacora, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 90, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Modificar producto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 90, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 90, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 90, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Agregar usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 90, 30));

        FondoCliente.setForeground(new java.awt.Color(153, 255, 153));
        FondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen_1.jpg"))); // NOI18N
        getContentPane().add(FondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -60, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Login vista = new Login();
        vista.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ConsultarProducto c = new ConsultarProducto(7);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitacoraActionPerformed
        Bitacora bita = new Bitacora();
        bita.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bitacoraActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            String[] productos = {"Abarrote", "Fresco", "Mercancia", "Personal"};
            String respuesta = (String) JOptionPane.showInputDialog(null, "Seleccione el producto a insertar", "Producto",
                    JOptionPane.DEFAULT_OPTION, null, productos, productos[0]);
            switch (respuesta) {
                case "Abarrote":
                    InsertarProducto ean = new InsertarProducto(7, 1);
                    ean.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Fresco":
                    InsertarPLU plu = new InsertarPLU(7);
                    plu.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Mercancia":
                    InsertarProducto ean2 = new InsertarProducto(7, 3);
                    ean2.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Personal":
                    InsertarProducto ean3 = new InsertarProducto(7, 4);
                    ean3.setVisible(true);
                    this.setVisible(false);
                    break;
                default:
                    break;
            }
        } catch (NullPointerException e) {
            Object[] message = {"Se ha cancelado"};
            JOptionPane.showMessageDialog(PrincipalSistemas.this, message, "Error", JOptionPane.OK_OPTION);
            String[] productos = {"Abarrote", "Fresco", "Mercancia", "Personal"};
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            String[] productos = {"Abarrote", "Fresco", "Mercancia", "Personal"};
            String respuesta = (String) JOptionPane.showInputDialog(null, "Seleccione el producto a insertar", "Producto",
                    JOptionPane.DEFAULT_OPTION, null, productos, productos[0]);
            switch (respuesta) {
                case "Abarrote":
                    BorrarProducto ean = new BorrarProducto(7, 1);
                    ean.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Fresco":
                    BorrarProducto plu = new BorrarProducto(7, 2);
                    plu.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Mercancia":
                    BorrarProducto ean2 = new BorrarProducto(7, 3);
                    ean2.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Personal":
                    BorrarProducto ean3 = new BorrarProducto(7, 4);
                    ean3.setVisible(true);
                    this.setVisible(false);
                    break;
                default:
                    break;
            }
        } catch (NullPointerException e) {
            Object[] message = {"Se ha cancelado"};
            JOptionPane.showMessageDialog(PrincipalSistemas.this, message, "Error", JOptionPane.OK_OPTION);
            String[] productos = {"Abarrote", "Fresco", "Mercancia", "Personal"};
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            String[] productos = {"Abarrote", "Fresco", "Mercancia", "Personal"};
            String respuesta = (String) JOptionPane.showInputDialog(null, "Seleccione el producto a insertar", "Producto",
                    JOptionPane.DEFAULT_OPTION, null, productos, productos[0]);
            switch (respuesta) {
                case "Abarrote":
                    ModificarEAN mod = new ModificarEAN(7, 1);
                    mod.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Fresco":
                    ModificarPLU mod2 = new ModificarPLU(7);
                    mod2.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Mercancia":
                    ModificarEAN mod3 = new ModificarEAN(7, 2);
                    mod3.setVisible(true);
                    this.setVisible(false);
                    break;
                case "Personal":
                    ModificarEAN mod4 = new ModificarEAN(7, 3);
                    mod4.setVisible(true);
                    this.setVisible(false);
                    break;
                default:
                    break;
            }
        } catch (NullPointerException e) {
            Object[] message = {"Se ha cancelado"};
            JOptionPane.showMessageDialog(PrincipalSistemas.this, message, "Error", JOptionPane.OK_OPTION);
            String[] productos = {"Abarrote", "Fresco", "Mercancia", "Personal"};
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        RegistrarUsuario u = new RegistrarUsuario();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalSistemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoCliente;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton bitacora;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
